import socket
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.connect(('127.0.0.1', 8080))
print("Connection established...")
client.send("Hello".encode())
print("massage sent")
server = client.recv(4096)
client.close()
print("Massage from server:",server.decode())
print("Connection disconnected")
